#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DT.Samples.Agora.Conference.Droid.Resource", IsApplication=true)]

namespace DT.Samples.Agora.Conference.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7F010000
			public const int profile_title_array = 2130771968;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F020000
			public const int colorAccent = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int colorPrimary = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int colorPrimaryDark = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int colorPrimarySemiTransparent = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int navigationBarColor = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int textColorPrimary = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int windowBackground = 2130837510;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F030000
			public const int activity_horizontal_margin = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int activity_vertical_margin = 2130903041;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F040000
			public const int green_button = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int ic_cam_active_call = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int ic_cam_disabled_call = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int ic_connection_0 = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int ic_connection_1 = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int ic_connection_2 = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int ic_connection_3 = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int ic_connection_4 = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int ic_connection_5 = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int ic_dots_menu_call = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public const int ic_end_call = 2130968586;
			
			// aapt resource value: 0x7F04000B
			public const int ic_hand = 2130968587;
			
			// aapt resource value: 0x7F04000C
			public const int ic_hand_selected = 2130968588;
			
			// aapt resource value: 0x7F04000D
			public const int ic_logo_agora = 2130968589;
			
			// aapt resource value: 0x7F04000E
			public const int ic_logo_dt = 2130968590;
			
			// aapt resource value: 0x7F04000F
			public const int ic_mic_active_call = 2130968591;
			
			// aapt resource value: 0x7F040010
			public const int ic_mic_inactive_call = 2130968592;
			
			// aapt resource value: 0x7F040011
			public const int ic_mic_muted_call = 2130968593;
			
			// aapt resource value: 0x7F040012
			public const int ic_settings_main = 2130968594;
			
			// aapt resource value: 0x7F040013
			public const int ic_share_main = 2130968595;
			
			// aapt resource value: 0x7F040014
			public const int ic_switch_camera_call = 2130968596;
			
			// aapt resource value: 0x7F040015
			public const int rounded_shadow_shape = 2130968597;
			
			// aapt resource value: 0x7F040016
			public const int rounded_video_shape = 2130968598;
			
			// aapt resource value: 0x7F040017
			public const int rounded_video_shape_opaque = 2130968599;
			
			// aapt resource value: 0x7F040018
			public const int splash_screen = 2130968600;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F050000
			public const int activity_video_chat_view = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int agora_version_text = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int audio_muted = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int audio_overlay = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int bitrate_value = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int channelName = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int debug_data = 2131034118;
			
			// aapt resource value: 0x7F050007
			public const int encryptionKey = 2131034119;
			
			// aapt resource value: 0x7F050008
			public const int end_call_button = 2131034120;
			
			// aapt resource value: 0x7F050009
			public const int framerate_value = 2131034121;
			
			// aapt resource value: 0x7F05000A
			public const int hand_image = 2131034122;
			
			// aapt resource value: 0x7F05000B
			public const int hand_up_button = 2131034123;
			
			// aapt resource value: 0x7F05000C
			public const int joinButton = 2131034124;
			
			// aapt resource value: 0x7F05000D
			public const int joinLayout = 2131034125;
			
			// aapt resource value: 0x7F05000E
			public const int local_video_container = 2131034126;
			
			// aapt resource value: 0x7F05000F
			public const int local_video_muted = 2131034127;
			
			// aapt resource value: 0x7F050010
			public const int local_video_overlay = 2131034128;
			
			// aapt resource value: 0x7F050011
			public const int local_video_view_container = 2131034129;
			
			// aapt resource value: 0x7F050012
			public const int menu_settings = 2131034130;
			
			// aapt resource value: 0x7F050013
			public const int menu_share = 2131034131;
			
			// aapt resource value: 0x7F050014
			public const int mute_audio_button = 2131034132;
			
			// aapt resource value: 0x7F050015
			public const int mute_video_button = 2131034133;
			
			// aapt resource value: 0x7F050016
			public const int name_value = 2131034134;
			
			// aapt resource value: 0x7F050017
			public const int profileSpinner = 2131034135;
			
			// aapt resource value: 0x7F050018
			public const int progress_bar = 2131034136;
			
			// aapt resource value: 0x7F050019
			public const int quality_image = 2131034137;
			
			// aapt resource value: 0x7F05001A
			public const int quality_text = 2131034138;
			
			// aapt resource value: 0x7F05001C
			public const int remote_videos_container = 2131034140;
			
			// aapt resource value: 0x7F05001D
			public const int remote_videos_scroll = 2131034141;
			
			// aapt resource value: 0x7F05001B
			public const int remote_video_view_container = 2131034139;
			
			// aapt resource value: 0x7F05001E
			public const int resolution_value = 2131034142;
			
			// aapt resource value: 0x7F05001F
			public const int room_name = 2131034143;
			
			// aapt resource value: 0x7F050020
			public const int switch_cam_button = 2131034144;
			
			// aapt resource value: 0x7F050021
			public const int useMySettingsSwitch = 2131034145;
			
			// aapt resource value: 0x7F050022
			public const int video_overlay = 2131034146;
			
			// aapt resource value: 0x7F050023
			public const int video_view_container = 2131034147;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F060000
			public const int Join = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int RemoteVideo = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int Room = 2131099650;
			
			// aapt resource value: 0x7F060003
			public const int Settings = 2131099651;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7F070000
			public const int top_menu = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F080000
			public const int app_icon = 2131230720;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F090000
			public const int app_name = 2131296256;
			
			// aapt resource value: 0x7F090001
			public const int join_button = 2131296257;
			
			// aapt resource value: 0x7F090002
			public const int join_description = 2131296258;
			
			// aapt resource value: 0x7F090003
			public const int permissions_not_granted = 2131296259;
			
			// aapt resource value: 0x7F090004
			public const int powered_by = 2131296260;
			
			// aapt resource value: 0x7F090005
			public const int profile_prompt = 2131296261;
			
			// aapt resource value: 0x7F090006
			public const int settings_bitrate = 2131296262;
			
			// aapt resource value: 0x7F090007
			public const int settings_framerate = 2131296263;
			
			// aapt resource value: 0x7F090008
			public const int settings_name = 2131296264;
			
			// aapt resource value: 0x7F090009
			public const int settings_profile = 2131296265;
			
			// aapt resource value: 0x7F09000A
			public const int settings_resolution = 2131296266;
			
			// aapt resource value: 0x7F09000B
			public const int settings_usemy = 2131296267;
			
			// aapt resource value: 0x7F09000C
			public const int splash_greetings = 2131296268;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F0A0000
			public const int DT_ActionBar = 2131361792;
			
			// aapt resource value: 0x7F0A0001
			public const int DT_Theme = 2131361793;
			
			// aapt resource value: 0x7F0A0002
			public const int DT_Theme_Base = 2131361794;
			
			// aapt resource value: 0x7F0A0003
			public const int DT_Theme_Room = 2131361795;
			
			// aapt resource value: 0x7F0A0004
			public const int DT_Theme_Splash = 2131361796;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
