// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using System.Collections.Generic;
using Xamarin.Agora.Mac;

namespace DT.Samples.Agora.Voice.Mac
{
	public partial class DeviceSelectionViewController : NSViewController
	{
        private readonly List<AgoraRtcDeviceInfo> connectedRecordingDevices = new List<AgoraRtcDeviceInfo>();
        private readonly List<AgoraRtcDeviceInfo> connectedPlaybackDevices = new List<AgoraRtcDeviceInfo>();
        private AgoraRtcEngineKit _agoraKit;

        public DeviceSelectionViewController(IntPtr handle) : base(handle)
        {
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            PreferredContentSize = new CoreGraphics.CGSize(500, 250);
        }

        private void LoadDevicesInPopUpButtons()
        {
            FillInDeviceSelection(MediaDeviceType.AudioRecording, microphoneSelection, connectedRecordingDevices);
            FillInDeviceSelection(MediaDeviceType.AudioPlayout, speakerSelection, connectedPlaybackDevices);
        }

        private void FillInDeviceSelection(MediaDeviceType deviceType, NSPopUpButton deviceSelection, List<AgoraRtcDeviceInfo> deviceMap)
        {
            deviceSelection.RemoveAllItems();
            deviceMap.Clear();
            var devices = _agoraKit.EnumerateDevices(deviceType);
            foreach (var device in devices)
            {
                deviceSelection.AddItem(device.DeviceName);
                deviceMap.Add(device);
            }
        }

        internal void SetAgoraKit(AgoraRtcEngineKit agoraKit)
        {
            _agoraKit = agoraKit;
            _agoraKit.MediaDeviceStateChanged += OnAgoraDeviceTypeStateChanged;
            LoadDevicesInPopUpButtons();
        }

        partial void didClickConfirmButton(NSButton sender)
        {
            var recordingDevice = connectedRecordingDevices[(int)microphoneSelection.IndexOfSelectedItem]?.DeviceId;
            if (!string.IsNullOrEmpty(recordingDevice))
            {
                _agoraKit.SetDevice(MediaDeviceType.AudioRecording, recordingDevice);
            }

            var playbackDevice = connectedPlaybackDevices[(int)speakerSelection.IndexOfSelectedItem]?.DeviceId;
            if (!string.IsNullOrEmpty(playbackDevice))
            {
                _agoraKit.SetDevice(MediaDeviceType.AudioPlayout, playbackDevice);
            }
            DismissViewController(this);
        }

        private void OnAgoraDeviceTypeStateChanged(object sender, MediaDeviceStateChangedEventArgs e)
        {
            BeginInvokeOnMainThread(LoadDevicesInPopUpButtons);
        }
    }
}
